### PR TITLE
🐛 Avoid timeout errors

### LINKED ISSUE #43: Time out if input is received while tests are running
```
** (exit) exited in: GenServer.call(MixTestInteractive.InteractiveMode, {:command, "\n"}, 5000)
    ** (EXIT) time out
    (elixir 1.11.3) lib/gen_server.ex:1027: GenServer.call/3
    (mix_test_interactive 1.0.0) lib/mix_test_interactive.ex:23: MixTestInteractive.loop/0
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

Steps to reproduce: 
* mix test.interactive
* press enter while tests are running, and if it takes more than 5 seconds, task exits

### PR DESCRIPTION
**Pull request by randycoulman**
Fixes #43 

When a command is entered during a long test run, a GenServer timeout would be raised.

To fix this, `InteractiveMode.process_command` now uses `cast` instead of `call` so that the read loop doesn't block on commands.

To make this work, we now have to use `System.stop` for the `quit` command rather than returning a `:quit` atom and allowing the loop to exit naturally.

`System.stop` takes just enough time that it seems like the quit command was ignored, so I also added a `Shutting down...` message to make it clear that something is happening.

### CODE REVIEW

File: lib/mix_test_interactive/interactive_mode.ex [hunk 1]
```diff
@@ -38,10 +38,10 @@ defmodule MixTestInteractive.InteractiveMode do
   @doc """
   Process a command from the user.
   """
-  @spec process_command(String.t()) :: :ok | :quit
-  @spec process_command(GenServer.server(), String.t()) :: :ok | :quit
+  @spec process_command(String.t()) :: :ok
+  @spec process_command(GenServer.server(), String.t()) :: :ok
   def process_command(server \\ __MODULE__, command) do
-    GenServer.call(server, {:command, command})
+    GenServer.cast(server, {:command, command})
```
Comment (OfTheDelmer) [inline lib/mix_test_interactive/interactive_mode.ex:44]: I was wondering about a few things here:

* Should we differentiate this as a `process_command_async`?
* Are we able to queue up a command while another command is processing?

There are things I like about an automatic timeout using `call`. I wonder if we'd be able to handle the cli args in such a way to allow cancellation if the user realizes the run is taking too long. I'd also like to be careful about  allowing queuing up calls in the server during a long running test run.

File: lib/mix_test_interactive/interactive_mode.ex [hunk 2]
```diff
@@ -65,36 +65,38 @@ defmodule MixTestInteractive.InteractiveMode do
...
-        {:reply, :ok, state}
+        {:noreply, state}
 
       :unknown ->
-        {:reply, :ok, state}
+        {:noreply, state}
 
       :quit ->
-        {:reply, :quit, state}
+        IO.puts("Shutting down...")
```
Comment (OfTheDelmer) [inline lib/mix_test_interactive/interactive_mode.ex:94]: There's a beautiful opportunity for a real show stopper function call: 🤩 

```suggestion
       show_stop()
```

**Review by OfTheDelmer — APPROVED** [review]

File: lib/mix_test_interactive/interactive_mode.ex (hunk 1 above)
Comment (randycoulman) [reply lib/mix_test_interactive/interactive_mode.ex:44]: This is the only caller of `process_command` (other than tests), so IMO it doesn't need a different name.

Yes, we can queue up a command. The intention is to make this work the same as a shell in a terminal. If a long-running command is running, the shell will process any commands typed during the run once the command completes.  Given that analogy, I'm not worried about queueing up calls to the GenServer.

In terms of cancelling a test run, that's a feature I've thought about a bit, but haven't implemented yet.

File: lib/mix_test_interactive/interactive_mode.ex (hunk 2 above)
Comment (randycoulman) [reply lib/mix_test_interactive/interactive_mode.ex:94]: lol
